[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dxforge"
version = "0.1.0"
description = "An orchestration suite for quantitative trading strategies."
requires-python = ">=3.10"
dependencies = [
    "apscheduler>=3.11.0",
    "bcrypt>=5.0.0",
    "docker-py>=1.10.6",
    "pyjwt>=2.10.1",
    "pyyaml>=6.0.3",
]
authors = [{ name = "Rafael Zimmer", email = "rzimmerdev@gmail.com" }]
license = "MIT"
readme = "README.md"

[project.scripts]
mycli = "__main__:main"

[tool.setuptools]
package-dir = { "" = "dxforge" }

[tool.setuptools.packages.find]
where = ["cli"]
