# Use a base Python image
FROM python:3.10

# Set the working directory in the container
WORKDIR /strategy

COPY requirements.txt .
RUN pip install -r requirements.txt

# Install any additional dependencies if needed
