controller:
    name: "feeds"
    path: "controllers/feeds/"
    nodes:
        feed:
            config: "config.yaml"
            path: "feed/"
        yfinance:
            config: "config.yaml"
            info: "info.yaml"
            path: "yfinance/"
        robobanker:
            config: "config.yaml"
            path: "rb-feed/"
networks:
    dxforge:
        external: true