# Dockerfile for running simple python http server
# Use the official image as a parent image
FROM python:3.7-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Run -m http.server with port 8000
CMD [ "python", "-m", "http.server", "8000" ]