from __future__ import annotations

import secrets as _secrets
from pathlib import Path

SECRETS_DIRNAME = "secrets"
SECRET_MODE = 0o600
DIR_MODE = 0o700

_LITERAL_ROOTS: dict[str, str] = {
    "minio_root_user.txt": "forge-root",
    "postgres_app_user.txt": "forge_app",
}

_RANDOM_ROOTS: tuple[str, ...] = (
    "postgres_password.txt",
    "minio_root_password.txt",
    "postgres_app_password.txt",
    "api_key_pepper.txt",
)

TOKEN_BYTES = 24


def random_token(nbytes: int = TOKEN_BYTES) -> str:
    """URL-safe, because these values get interpolated into database URLs."""
    return _secrets.token_urlsafe(nbytes)


def write_secret(path: Path, value: str) -> None:
    # No trailing newline: consumers range from shell ``$(cat file)`` to
    # MinIO-style credential readers that reject the whitespace.
    path.write_text(value, encoding="utf-8")
    path.chmod(SECRET_MODE)


COMPOSE_ENV_NAME = "compose.env"

# a missing secret interpolates to empty, which the template rejects via ${VAR:?}
_COMPOSE_ENV_SOURCES: tuple[tuple[str, str], ...] = (
    ("POSTGRES_PASSWORD", "postgres_password.txt"),
    ("POSTGRES_APP_USER", "postgres_app_user.txt"),
    ("POSTGRES_APP_PASSWORD", "postgres_app_password.txt"),
    ("MINIO_ROOT_USER", "minio_root_user.txt"),
    ("MINIO_ROOT_PASSWORD", "minio_root_password.txt"),
)


def write_compose_env(root: Path) -> Path:
    directory = root / SECRETS_DIRNAME
    directory.mkdir(parents=True, exist_ok=True)
    lines = [
        "# generated by dxforge from ./secrets; do not edit",
        *(
            f"{var}={read_secret(root, name) or ''}"
            for var, name in _COMPOSE_ENV_SOURCES
        ),
    ]
    target = directory / COMPOSE_ENV_NAME
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    target.chmod(SECRET_MODE)
    return target


def generate_root_secrets(root: Path) -> list[str]:
    directory = root / SECRETS_DIRNAME
    directory.mkdir(parents=True, exist_ok=True)
    directory.chmod(DIR_MODE)

    created: list[str] = []
    for name, value in _LITERAL_ROOTS.items():
        target = directory / name
        if not target.exists():
            write_secret(target, value)
            created.append(name)
    for name in _RANDOM_ROOTS:
        target = directory / name
        if not target.exists():
            write_secret(target, random_token())
            created.append(name)
    return created


def read_secret(root: Path, name: str) -> str | None:
    path = root / SECRETS_DIRNAME / name
    if not path.is_file():
        return None
    return path.read_text(encoding="utf-8").strip()
