controller:
  name: "strategies"
  path: "controllers/strategies/"
  strategy:
    config: "strategy/config.yaml"
    path: "strategy/"
  rsi-strategy:
    config: "rsi-strategy/config.yaml"
    path: "rsi-strategy/"

networks:
  dxforge:
    external: true